insert into public.employees (
  legacy_mock_id,
  name,
  role,
  email,
  initials,
  is_seed_data,
  seed_batch
)
values
  ('u-ben', 'Ben Sledge', 'admin', 'ben@sledge.co', 'BS', true, 'phase_1_core_seed_2026_05_15'),
  ('u-sarah', 'Sarah Holm', 'supervisor', 'sarah@sledge.co', 'SH', true, 'phase_1_core_seed_2026_05_15'),
  ('u-mike', 'Mike Doran', 'employee', 'mike@sledge.co', 'MD', true, 'phase_1_core_seed_2026_05_15'),
  ('u-jake', 'Jake Reilly', 'employee', 'jake@sledge.co', 'JR', true, 'phase_1_core_seed_2026_05_15'),
  ('u-tanya', 'Tanya Webb', 'employee', 'tanya@sledge.co', 'TW', true, 'phase_1_core_seed_2026_05_15')
on conflict (legacy_mock_id) do update set
  name = excluded.name,
  role = excluded.role,
  email = excluded.email,
  initials = excluded.initials,
  is_seed_data = excluded.is_seed_data,
  seed_batch = excluded.seed_batch;

insert into public.jobs (
  legacy_mock_id,
  name,
  job_number,
  client_name,
  address,
  status,
  start_date,
  end_date,
  supervisor_employee_id,
  hours_logged,
  latitude,
  longitude,
  service_type,
  notes,
  is_seed_data,
  seed_batch
)
values
  (
    'job-riverfront',
    'Riverfront Commercial Build',
    'SC-2026-014',
    'Northgate Holdings',
    '1820 Riverfront Dr, Calgary, AB',
    'active',
    '2026-04-12',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    412,
    51.0421,
    -114.0533,
    'Foundation & Structural',
    'Large commercial foundation pour. Weather delays possible due to April conditions. Client requests weekly progress photos.',
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-maple',
    'Maple Street Residential',
    'SC-2026-018',
    'Holm Family',
    '44 Maple St, Calgary, AB',
    'active',
    '2026-04-28',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    96,
    51.0586,
    -114.0708,
    'Driveway & Patio',
    'Residential driveway replacement. Homeowners need driveway access for parking by May 15.',
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-hwy2',
    'Highway 2 Retaining Wall',
    'SC-2026-009',
    'AB Transportation',
    'Hwy 2 km 14, Airdrie, AB',
    'hold',
    '2026-03-02',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    184,
    51.2917,
    -114.0144,
    'Retaining Wall & Excavation',
    'Highway infrastructure project. Traffic control in place. Awaiting geotechnical assessment.',
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-eastside',
    'Eastside Warehouse Slab',
    'SC-2026-021',
    'BlueLine Logistics',
    '2200 32 Ave NE, Calgary, AB',
    'active',
    '2026-04-20',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    240,
    51.0884,
    -113.9842,
    'Warehouse Floor',
    'Large industrial warehouse concrete floor. Multiple pours planned over 3 weeks.',
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-glenmore',
    'Glenmore Sidewalk Replacement',
    'SC-2025-098',
    'City of Calgary',
    'Glenmore Trail SW, Calgary, AB',
    'completed',
    '2025-09-15',
    '2025-11-22',
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    612,
    50.9928,
    -114.1064,
    'Sidewalk & Path',
    'Municipal sidewalk repair completed ahead of schedule.',
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-okotoks',
    'Okotoks Foundation Pour',
    'SC-2025-104',
    'Stonebridge Homes',
    '85 Westridge Dr, Okotoks, AB',
    'completed',
    '2025-10-04',
    '2025-12-10',
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    488,
    50.7256,
    -113.9756,
    'Residential Foundation',
    'New home foundation completed. House framing started.',
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-sundre-plaza',
    'Sundre Town Plaza Expansion',
    'SC-2026-031',
    'Sundre Municipal',
    'Main St, Sundre, AB',
    'active',
    '2026-04-01',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    156,
    52.1289,
    -114.8689,
    'Municipal Plaza',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-carstairs-driveway',
    'Carstairs Residential Driveway',
    'SC-2026-027',
    'Peterson Family',
    '1245 Railway Ave, Carstairs, AB',
    'active',
    '2026-05-02',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    72,
    51.6523,
    -114.0934,
    'Driveway & Patio',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-olds-foundation',
    'Olds Commercial Foundation',
    'SC-2026-025',
    'Olds Business Corp',
    'Highway 27, Olds, AB',
    'active',
    '2026-04-15',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    328,
    51.7987,
    -114.2891,
    'Commercial Foundation',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-didsbury-parking',
    'Didsbury Parking Lot',
    'SC-2026-029',
    'Didsbury County',
    '20 Ave, Didsbury, AB',
    'hold',
    '2026-03-20',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    144,
    51.9834,
    -114.2634,
    'Parking Lot',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-cremona-slab',
    'Cremona Farm Concrete Slab',
    'SC-2026-033',
    'Rocky Mountain Farms',
    'Range Rd 40, Cremona, AB',
    'active',
    '2026-04-25',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    88,
    52.0412,
    -113.9876,
    'Agricultural Slab',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-dogpound-pad',
    'Dog Pound Shed Pad',
    'SC-2026-026',
    'Dog Pound Equestrian',
    'Township Rd 300, Dog Pound, AB',
    'completed',
    '2026-02-10',
    '2026-03-15',
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    264,
    51.8267,
    -113.9854,
    'Agricultural Slab',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-sundre-municipal',
    'Sundre Municipal Building Slab',
    'SC-2026-035',
    'Town of Sundre',
    'Centre St, Sundre, AB',
    'hold',
    '2026-03-10',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    216,
    52.1401,
    -114.8734,
    'Municipal Building',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-carstairs-sidewalk',
    'Carstairs Sidewalk Repair',
    'SC-2025-099',
    'Carstairs MD',
    'Station Rd, Carstairs, AB',
    'completed',
    '2025-11-01',
    '2025-12-20',
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    320,
    51.6589,
    -114.0878,
    'Sidewalk & Path',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-olds-warehouse',
    'Olds Industrial Warehouse Pour',
    'SC-2026-032',
    'Progressive Industries',
    'Industrial Park, Olds, AB',
    'active',
    '2026-04-08',
    null,
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    264,
    51.8045,
    -114.2756,
    'Warehouse Floor',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  ),
  (
    'job-didsbury-residential',
    'Didsbury Residential Complex',
    'SC-2026-028',
    'Didsbury Developments',
    '10 St, Didsbury, AB',
    'completed',
    '2025-12-01',
    '2026-02-28',
    (select id from public.employees where legacy_mock_id = 'u-sarah'),
    512,
    51.9756,
    -114.2567,
    'Residential Complex',
    null,
    true,
    'phase_1_core_seed_2026_05_15'
  )
on conflict (legacy_mock_id) do update set
  name = excluded.name,
  job_number = excluded.job_number,
  client_name = excluded.client_name,
  address = excluded.address,
  status = excluded.status,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  supervisor_employee_id = excluded.supervisor_employee_id,
  hours_logged = excluded.hours_logged,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  service_type = excluded.service_type,
  notes = excluded.notes,
  is_seed_data = excluded.is_seed_data,
  seed_batch = excluded.seed_batch;

insert into public.job_crew (
  job_id,
  employee_id,
  role_on_job,
  is_seed_data,
  seed_batch
)
select
  j.id,
  e.id,
  'crew',
  true,
  'phase_1_core_seed_2026_05_15'
from (
  values
    ('job-riverfront', 'u-mike'),
    ('job-riverfront', 'u-jake'),
    ('job-riverfront', 'u-tanya'),
    ('job-maple', 'u-mike'),
    ('job-maple', 'u-jake'),
    ('job-hwy2', 'u-tanya'),
    ('job-eastside', 'u-mike'),
    ('job-glenmore', 'u-jake'),
    ('job-glenmore', 'u-tanya'),
    ('job-okotoks', 'u-mike'),
    ('job-okotoks', 'u-jake'),
    ('job-sundre-plaza', 'u-mike'),
    ('job-sundre-plaza', 'u-tanya'),
    ('job-carstairs-driveway', 'u-jake'),
    ('job-olds-foundation', 'u-mike'),
    ('job-olds-foundation', 'u-jake'),
    ('job-olds-foundation', 'u-tanya'),
    ('job-didsbury-parking', 'u-mike'),
    ('job-cremona-slab', 'u-tanya'),
    ('job-dogpound-pad', 'u-jake'),
    ('job-dogpound-pad', 'u-tanya'),
    ('job-sundre-municipal', 'u-mike'),
    ('job-sundre-municipal', 'u-jake'),
    ('job-carstairs-sidewalk', 'u-tanya'),
    ('job-olds-warehouse', 'u-mike'),
    ('job-olds-warehouse', 'u-jake'),
    ('job-didsbury-residential', 'u-mike'),
    ('job-didsbury-residential', 'u-tanya')
) as crew(legacy_job_id, legacy_employee_id)
join public.jobs j on j.legacy_mock_id = crew.legacy_job_id
join public.employees e on e.legacy_mock_id = crew.legacy_employee_id
on conflict (job_id, employee_id) do update set
  role_on_job = excluded.role_on_job,
  is_seed_data = excluded.is_seed_data,
  seed_batch = excluded.seed_batch;

insert into public.job_activity (
  legacy_mock_id,
  job_id,
  activity_type,
  actor_employee_id,
  occurred_at,
  detail,
  is_seed_data,
  seed_batch
)
select
  activity.legacy_mock_id,
  j.id,
  activity.activity_type::public.job_activity_type,
  e.id,
  activity.occurred_at::timestamptz,
  activity.detail,
  true,
  'phase_1_core_seed_2026_05_15'
from (
  values
    ('a-1', 'job-riverfront', 'clock-in', 'u-mike', '2026-05-07T07:02:00Z', 'Clocked in'),
    ('a-2', 'job-riverfront', 'note', 'u-sarah', '2026-05-06T16:30:00Z', 'Weather delays expected tomorrow due to rain forecast. May need to reschedule concrete pour to next week.'),
    ('a-3', 'job-riverfront', 'upload', 'u-mike', '2026-05-04T16:11:00Z', 'Uploaded pour-day-east.jpg'),
    ('a-4', 'job-riverfront', 'sign-off', 'u-sarah', '2026-05-04T07:30:00Z', 'Daily safety sign-off'),
    ('a-5', 'job-riverfront', 'note', 'u-mike', '2026-05-03T15:45:00Z', 'East footing excavation complete. Ready for rebar placement on Monday.'),
    ('a-6', 'job-riverfront', 'note', 'u-jake', '2026-05-02T14:20:00Z', 'Materials delivered: 50 cu yards of ready-mix concrete. Stored at site north corner.'),
    ('a-7', 'job-riverfront', 'note', 'u-sarah', '2026-04-30T10:15:00Z', 'Client site walk-through completed. Approved foundation layout. No changes needed.'),
    ('a-4', 'job-maple', 'note', 'u-sarah', '2026-05-06T14:00:00Z', 'Foundation inspection scheduled'),
    ('a-5', 'job-hwy2', 'clock-out', 'u-tanya', '2026-04-20T17:00:00Z', 'Clocked out')
) as activity(legacy_mock_id, legacy_job_id, activity_type, legacy_actor_id, occurred_at, detail)
join public.jobs j on j.legacy_mock_id = activity.legacy_job_id
left join public.employees e on e.legacy_mock_id = activity.legacy_actor_id
on conflict (job_id, legacy_mock_id) where legacy_mock_id is not null do update set
  activity_type = excluded.activity_type,
  actor_employee_id = excluded.actor_employee_id,
  occurred_at = excluded.occurred_at,
  detail = excluded.detail,
  is_seed_data = excluded.is_seed_data,
  seed_batch = excluded.seed_batch;
